### **Soal 1 Pandas Data Frame**

In [90]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np
# generate dataset
X, Y = make_regression(n_samples=100, n_features=100, n_informative=10)

#membuat dataframe dari x dan y
df = pd.DataFrame(X)
df.columns = ['X' + str(i) for i in range(100)]
df['Y'] = Y
df

X0        X1        X2        X3        X4        X5        X6  \
0   1.913275  0.717565  0.073107  2.103303 -0.118061 -0.730246 -1.506293   
1  -0.635114 -0.382686 -0.163456  1.554069 -1.828024 -0.236354  0.815176   
2  -0.129673  0.247942 -0.382793  0.986426 -1.229758  1.517594 -1.854709   
3  -0.659368 -0.042602  0.673757  0.871577 -0.719124 -1.806361  0.819433   
4  -0.367063  0.120002  0.279921 -0.919261 -0.669246  1.093528 -0.511747   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.011399 -0.379423 -0.638001  1.177477 -1.066694 -0.358287  0.544468   
96 -1.547936  0.434947 -0.933949 -0.459904 -0.481652 -0.794308  0.123387   
97 -0.426672 -0.505214 -1.652025 -2.961586  1.181665 -2.108308  1.318831   
98  0.186217 -1.159608  0.660167  2.450345  0.397385  0.094862 -0.518732   
99  2.220548  1.460709 -0.136215 -0.200558  0.939006 -0.908713  0.021121   

          X7        X8        X9  ...       X91       X92       X93       X94  \
0   0.626858  0.843313 -0.868026  ...  2.212147 -0.872651  0.632463 -0.614715   
1   0.638138 -1.360789 -1.423460  ...  0.032201 -1.597235  0.649391  0.100589   
2  -0.952626 -1.083801 -1.815906  ... -0.498276  0.423918 -1.176569  0.054964   
3   0.013251 -1.999945 -0.143016  ... -1.068028  0.200261  0.001744 -0.691898   
4   0.091871  0.016346 -0.029026  ... -0.871380  0.140230  1.452998  0.523073   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95 -0.305992  0.770232  0.293033  ...  0.205757  1.315485  1.237864  0.793024   
96 -0.511740  0.509032 -0.368538  ... -1.275265 -0.371647  0.628429 -1.951391   
97  0.888455  0.253254  1.314619  ...  1.573814  1.659317 -0.065706 -2.126420   
98  0.818329  1.224955  0.901043  ...  0.064608 -0.024547 -1.176229  0.521270   
99  2.381755 -0.161003 -0.088584  ...  0.069863  0.780910  1.596207  0.495557   

         X95       X96       X97       X98       X99           Y  
0   1.021079 -1.285653  0.124494  0.748096  0.171657 -100.256352  
1   0.644298  0.972071  1.581009 -0.936133  0.929588 -204.070782  
2  -0.472370  0.594831 -1.869697  0.448972  0.382262 -793.569280  
3   2.806645  0.391868 -0.171012  0.160150  1.255218  327.713531  
4  -0.939827 -0.175654 -0.655936 -1.223629 -0.207607 -109.748847  
..       ...       ...       ...       ...       ...         ...  
95  1.136629  0.690639  1.472691 -0.397793  0.253796 -114.594304  
96  2.015743 -0.277451 -0.837557 -1.783828  0.082397  217.116654  
97 -0.053447 -0.388100  0.600549 -0.408472 -0.890683  447.056175  
98 -0.379655  0.037324  0.589019  0.914542  0.073468  107.222953  
99  0.133698  1.436205 -0.516226  0.591731  0.066767   49.935261  

[100 rows x 101 columns]

Buatlah sebuah Dataframe dengan data di atas. Dimana terdapat variabel X dan y. buatlah menjadi column X0-X99 dan y pada akhir column.

In [2]:
#jangan di run
#cell contoh hasil

X0        X1        X2        X3        X4        X5        X6  \
0  -0.915212  1.493571  0.436189  0.705495 -1.761485 -1.249118 -0.407565   
1   0.878028 -0.140705 -0.944289 -0.174627  0.567625  0.300732  0.289273   
2   0.964140 -0.793125  0.841936  0.313088  0.199498  2.282574 -0.863335   
3  -0.882787 -1.152892  0.068783 -0.930178  0.036717 -0.197270  1.247525   
4   0.290320  0.316385 -2.246657  0.011012  0.311103  0.109057  0.308782   
..       ...       ...       ...       ...       ...       ...       ...   
95 -1.536589 -0.730357  0.779719  1.277046  1.321476 -1.119201 -0.092392   
96 -0.704000 -1.611241  1.814556  0.953647  0.076468  0.629419 -0.569326   
97  1.637832 -0.153730 -0.483074  1.892856  0.389054 -0.717983 -0.983700   
98 -1.167298 -0.260727  0.346849  1.693973 -0.097193  0.818206  0.813115   
99 -2.870851  0.489295 -0.686917  1.338321 -0.792317 -0.361618 -2.172565   

          X7        X8        X9  ...       X91       X92       X93       X94  \
0  -0.009842 -1.735053  0.910152  ... -0.621775  0.814272 -1.041435  1.895063   
1  -1.289092  0.686546  0.637312  ... -0.554019  0.193415  0.722733 -1.730579   
2  -0.191104  0.495262  0.223180  ... -0.262799 -2.593864  1.601533  1.455797   
3   0.474067 -0.704820 -1.593972  ...  0.092427  1.249872  2.186223 -0.131910   
4  -0.624079 -0.229622 -0.667855  ...  1.719986  2.142118  0.014183  1.037259   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.368560 -1.291459 -1.186540  ... -0.457575 -0.791506 -1.389717 -0.698408   
96  0.107478  1.417058 -1.063939  ... -2.022347 -0.064499  0.432952  0.398392   
97  0.753492  0.191647  0.197114  ...  0.241908  0.035325 -0.061961 -1.520946   
98 -0.566283 -1.620272 -0.536863  ...  0.324929  0.906779 -1.344463  0.633542   
99 -0.478471  0.227533 -1.606074  ...  0.425045 -1.007069 -0.782855  0.611999   

         X95       X96       X97       X98       X99           Y  
0  -1.436868  1.454175  0.394605  0.124696  1.926075 -100.608141  
1  -0.406840  2.340087 -0.114712  0.158274 -1.454759    1.689581  
2   0.058587  0.953225  0.752472  0.564658  1.131241  116.855979  
3   2.134867 -0.717014  0.083398 -0.772829  1.231793 -215.797817  
4  -1.227784 -1.471667 -0.911379 -0.068846  0.284262  197.679368  
..       ...       ...       ...       ...       ...         ...  
95 -0.989968  0.887914 -0.629646  0.654470 -1.453955 -109.582037  
96  1.301282  0.239558  1.705920  1.855406 -0.772279  177.805858  
97 -0.786646 -0.940910 -1.611571 -1.016891 -1.083254   36.836594  
98 -0.073089 -0.213599 -0.345081 -0.694501 -0.164250  390.464302  
99 -0.875159 -0.691232 -0.594701 -1.282145 -1.013643  133.545897  

[100 rows x 101 columns]

### Soal 02

Berapa banyak perenang yang memiliki medali perunggu(bronze)?

In [91]:
import pandas as pd
summer=pd.read_csv('summer.csv')
summer

Year    City      Sport           Discipline  \
0      1896  Athens   Aquatics             Swimming   
1      1896  Athens   Aquatics             Swimming   
2      1896  Athens   Aquatics             Swimming   
3      1896  Athens   Aquatics             Swimming   
4      1896  Athens   Aquatics             Swimming   
...     ...     ...        ...                  ...   
31160  2012  London  Wrestling  Wrestling Freestyle   
31161  2012  London  Wrestling  Wrestling Freestyle   
31162  2012  London  Wrestling  Wrestling Freestyle   
31163  2012  London  Wrestling  Wrestling Freestyle   
31164  2012  London  Wrestling  Wrestling Freestyle   

                         Athlete Country Gender                       Event  \
0                  HAJOS, Alfred     HUN    Men              100M Freestyle   
1               HERSCHMANN, Otto     AUT    Men              100M Freestyle   
2              DRIVAS, Dimitrios     GRE    Men  100M Freestyle For Sailors   
3             MALOKINIS, Ioannis     GRE    Men  100M Freestyle For Sailors   
4             CHASAPIS, Spiridon     GRE    Men  100M Freestyle For Sailors   
...                          ...     ...    ...                         ...   
31160         JANIKOWSKI, Damian     POL    Men                    Wg 84 KG   
31161  REZAEI, Ghasem Gholamreza     IRI    Men                    Wg 96 KG   
31162             TOTROV, Rustam     RUS    Men                    Wg 96 KG   
31163          ALEKSANYAN, Artur     ARM    Men                    Wg 96 KG   
31164             LIDBERG, Jimmy     SWE    Men                    Wg 96 KG   

        Medal  
0        Gold  
1      Silver  
2      Bronze  
3        Gold  
4      Silver  
...       ...  
31160  Bronze  
31161    Gold  
31162  Silver  
31163  Bronze  
31164  Bronze  

[31165 rows x 9 columns]

In [92]:
summer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31165 entries, 0 to 31164
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Year        31165 non-null  int64 
 1   City        31165 non-null  object
 2   Sport       31165 non-null  object
 3   Discipline  31165 non-null  object
 4   Athlete     31165 non-null  object
 5   Country     31161 non-null  object
 6   Gender      31165 non-null  object
 7   Event       31165 non-null  object
 8   Medal       31165 non-null  object
dtypes: int64(1), object(8)
memory usage: 2.1+ MB


In [93]:
summer.isnull().sum().sort_values(ascending=False)

Country       4
Year          0
City          0
Sport         0
Discipline    0
Athlete       0
Gender        0
Event         0
Medal         0
dtype: int64

In [94]:
# hitung jumlah perenang yang memiliki medali perunggu (bronze)
bronze_medal = summer[summer["Medal"] == "Bronze"]
athlete_count = bronze_medal["Athlete"].nunique()
athlete_count


9336

Answer:


Dalam olahraga air (Aquatics), kota mana yang memiliki rata-rata perolehan medali tertinggi?

In [104]:
# memfilter data yang hanya berisi olahraga akuatik
summer = summer[summer['Sport'].str.contains("Aquatics")]

# melakukan agregasi data berdasarkan kolom city dan menghitung rata-rata perolehan medal
grouped = summer.groupby(['Sport','City','Medal']).size().reset_index(name='counts')

# menentukan kolom sport dengan city mana yang memiliki rata-rata perolehan medal tertinggi
grouped = grouped.sort_values(by='counts', ascending=False)

print("Kota dengan rata-rata perolehan medal tertinggi pada olahraga akuatik:")
print(grouped.head(1))


Kota dengan rata-rata perolehan medal tertinggi pada olahraga akuatik:
       Sport    City Medal  counts
25  Aquatics  London  Gold     167


### **Soal 3 List Comprehension & Pandas** 

Pada Soal ini kalian **wajib** menggunakan feature list comprehension dan juga apply.<br>

In [105]:
import pandas as pd
Salaries=pd.read_csv('Salaries.csv')
Salaries

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [106]:
Salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


PT.A baru saja kena tegur dari negara karena ketauan tidak membayar uang lemburan. Anda sebagai seorang data Scientist diminta PT.A untuk mengolah data yang ada.

**Step pertama**

**Wajib Menggunakan .Apply()** <br>
PT.A melihat beberapa data tidak di isi oleh sebagian karyawan. kalian di minta untuk untuk merubah nilai 'Not provided' pada column `JobTitle` dan `EmployeeName` menjadi 'Error'.

In [107]:
#your code goes here

Salaries['EmployeeName'] = Salaries['EmployeeName'].apply(lambda x: 'Error' if x == 'Not provided' else x)
Salaries['JobTitle'] = Salaries['JobTitle'].apply(lambda x: 'Error' if x == 'Not provided' else x)
Salaries


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651              Error   
148651  148652              Error   
148652  148653              Error   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                           Error        NaN   
148651                                           Error        NaN   
148652                                           Error        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [28]:
#jangan tulis code disini
#cell contoh hasil:

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651              Error   
148651  148652              Error   
148652  148653              Error   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                           Error        NaN   
148651                                           Error        NaN   
148652                                           Error        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

**Step Kedua**

**WAJIB Gunakan list comprehension**<br>
Anda diminta untuk menambahkan 200000 pada karyawan yang mendapat Overtime 0 pada Data yang telah dibersihkan di tahap 1.


In [109]:
Salaries = [salary + 200000 if salary["OvertimePay"] == 0 else salary for salary in Salaries]



TypeError: string indices must be integers

In [29]:
#jangan tulis code disini
#cell contoh hasil:

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651              Error   
148651  148652              Error   
148652  148653              Error   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                           Error        NaN   
148651                                           Error        NaN   
148652                                           Error        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0         200000.00  400184.25       NaN  567595.43         567595.43  2011   
1         122565.94  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649    200000.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653    200000.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

**Tahap ketiga** 

**bebas memakai teknik apapun**<br>
selanjutnya ada kelasahan pada penulisan 'CAPTAIN III (POLICE DEPARTMENT)' ubahlah menjadi 'CAPTAIN III' saja

In [117]:
#your code goes here
# mengubah kolom yang berisi "CAPTAIN III (POLICE DEPARTMENT)" menjadi "CAPTAIN III"
Salaries['JobTitle'] = Salaries['JobTitle'].str.replace("CAPTAIN III(POLICE DEPARTMENT)", "CAPTAIN III",regex = False)
Salaries


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651              Error   
148651  148652              Error   
148652  148653              Error   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                                          CAPTAIN III  155966.02   
2                                          CAPTAIN III  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                           Error        NaN   
148651                                           Error        NaN   
148652                                           Error        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [30]:
#jangan tulis code disini
#cell contoh hasil:

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651              Error   
148651  148652              Error   
148652  148653              Error   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                                          CAPTAIN III  155966.02   
2                                          CAPTAIN III  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                           Error        NaN   
148651                                           Error        NaN   
148652                                           Error        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0         200000.00  400184.25       NaN  567595.43         567595.43  2011   
1         122565.94  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649    200000.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653    200000.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

### **Soal 4 One Hot Encoding**

Buatlah **sebuah fungsi** bernama `one_hot`, yang menerima input sebuah numpy array.

Ex:<br>
input array [2,3,1,2] maka hasil dari fungsi kalian:

array [[0,1,0], [0,0,1], [1,0,0], [0,1,0]]

Constrain: <br>

- Integers dalam input selalu di awali 1. 
- Integers dalam input hanya positif dan bukan 0.
- Integers dalam input tidak akan skip angka.

In [73]:
import numpy as np

def one_hot(arr):
    # mendapatkan jumlah unik dari input array
    uniq = np.unique(arr)
    n_classes = uniq.shape[0]
    
    # inisialisasi array one-hot encoding
    one_hot_encoded = np.zeros((arr.shape[0], n_classes), dtype=int)
    
    # mengisi nilai one-hot encoding sesuai dengan input array
    for i, value in enumerate(arr):
        index = np.where(uniq == value)[0][0]
        one_hot_encoded[i, index] = 1
        
    return one_hot_encoded


In [74]:
input_array = np.array([3,2,1,2,3,3,3])
output_array = one_hot(input_array)

print(output_array)


[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [3]:
#jangan tulis code disini
#cell contoh hasil:

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])